name: Deploy to Forpsi FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpx.forpsi.com
          username: www.janbozek.cz
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./
          server-dir: /www/strateg2026/
          exclude: |
            **/.git*/**
            **/.git*
            **/.vscode/**
            **/node_modules/**
